import mongoose from 'mongoose'
import 'dotenv/config'
import productModel from './models/productModel.js'

// Real product data fetched from live fitbae-backend.vercel.app
const products = [
  { name: "Floral Off-Shoulder Puff Sleeve Top", description: "This stylish off-shoulder top features a vibrant floral print in shades of purple, pink, and yellow. The design includes short puff sleeves with elasticated cuffs, creating a trendy and feminine silhouette perfect for casual outings or summer gatherings.", price: 50, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747662635/svv9s220diisycdlvaic.png"], category: "Women", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: true, date: 1747662634817 },
  { name: "Oversized Pink Polo Shirt with White Collar", description: "A stylish individual showcases a relaxed, modern look featuring an oversized light pink polo shirt with a contrasting white collar. The outfit is complemented by visible tattoos on both arms, adding a unique and edgy touch to the casual ensemble.", price: 45, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747662680/cglgudxzklwsrwzdmygc.png","https://res.cloudinary.com/dufsxpqd7/image/upload/v1747662680/athaz3lpylcw7anzukbf.png","https://res.cloudinary.com/dufsxpqd7/image/upload/v1747662680/qcsqbwjlpbbfgsyxfedg.png","https://res.cloudinary.com/dufsxpqd7/image/upload/v1747662680/errerwx8v2peuk3xpr9b.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: true, date: 1747662680156 },
  { name: "Floral Print Girls' Dress", description: "A charming girls' dress featuring a pastel floral print, long ruffled sleeves, and a flowy silhouette, perfect for spring or summer occasions.", price: 55, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663345/qxlwr8jvlw7zdoldamfs.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: true, date: 1747663345352 },
  { name: "Women's Black Puma Logo T-Shirt", description: "A fitted black women's t-shirt showcasing a large outlined Puma logo, combining comfort and sporty style for daily wear.", price: 25, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663400/hzi7mw25nvmnr5vhq92v.png"], category: "Women", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: true, date: 1747663400002 },
  { name: "Girls' Pink Top with White Skirt", description: "A cute girls' outfit featuring a textured pink short-sleeve top paired with a white, semi-sheer skirt, offering a playful and trendy look.", price: 35, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663436/vsh23fdz4qlnftmpzqdl.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: true, date: 1747663436336 },
  { name: "Men's Black Puma Graphic T-Shirt", description: "A casual black men's t-shirt with a bold Puma logo and geometric line design on the front, ideal for everyday wear or sporty looks.", price: 30, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663373/hasgof1kghpzyulqempr.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: true, date: 1747663372551 },
  { name: "Men's Navy Blue Slim-Fit Jeans", description: "Classic navy blue slim-fit jeans for men, featuring a modern cut and versatile style suitable for casual or semi-formal occasions.", price: 60, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663672/uhfzcywnrb2wlqat575a.png"], category: "Men", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747663671633 },
  { name: "Men's GAP Colorblock Rugby Shirt", description: "Long-sleeve rugby shirt for men from GAP, designed with a cream base and a bold olive green horizontal stripe, offering a sporty yet casual look.", price: 40, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663718/jjt0oxgorr7sxoxtthcj.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747663717682 },
  { name: "Girls' Light Blue Ruffle Sleeve Top", description: "Light blue girls' top with flutter sleeves and a front knot, adorned with a small embroidered floral detail, perfect for a playful and stylish outfit.", price: 50, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663753/jn58sxhagiewozoos0gi.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747663752715 },
  { name: "Men's Olive Green Cargo Joggers", description: "Olive green cargo jogger pants for men, featuring multiple utility pockets, zipper detailing, and elasticized cuffs for a trendy, functional style.", price: 20, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663783/wrnmvobukb03smsojpdk.png"], category: "Men", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747663783115 },
  { name: "Men's Boston Raglan T-Shirt", description: "A casual men's t-shirt featuring a beige body with contrasting maroon raglan sleeves and a \"Boston\" text print on the chest, delivering a sporty and relaxed style.", price: 30, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663863/brni0nuuqj7aqdi2v2w2.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747663862801 },
  { name: "Men's Classic White Crew Neck T-Shirt", description: "A simple and versatile men's white crew neck t-shirt, ideal for layering or wearing on its own for a clean, minimalist look.", price: 65, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747663889/g9v9cc6ujcwguwvhoud3.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747663889499 },
  { name: "Men's Blue Athletic Track Pants", description: "Sporty blue track pants for men, designed with a drawstring waist featuring red and white stripes, side pockets, and an athletic emblem, ideal for workouts or casual wear.", price: 49, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664044/by6tnm1swakpdy3eftte.png"], category: "Men", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664044200 },
  { name: "Girls' White Puff Sleeve Top with Beige Trousers", description: "A stylish girls' ensemble with a white puff sleeve top and delicate ruffle neckline, tucked into beige high-waisted trousers for a polished appearance.", price: 38, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664075/vh1jxyyl5ksffddoaig8.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664075227 },
  { name: "Men's Black Joggers with Graphic Print", description: "Black jogger pants for men, featuring a modern grey graphic print on one leg, an elastic waistband, and a tapered fit, perfect for both active and leisurewear.", price: 15, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664097/wtbgsinlo2omrfk6rbtd.png"], category: "Men", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664097239 },
  { name: "Boys' Navy Short Sleeve Shirt with White Tee", description: "A casual boys' outfit featuring a textured navy blue short sleeve button-up shirt layered over a white t-shirt, paired with light blue jeans for a relaxed look.", price: 28, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664015/abdwloczmumqxoytdmuc.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664014697 },
  { name: "Boys' White \"GOAL!\" Graphic T-Shirt", description: "A white short-sleeve t-shirt for boys, featuring a bold \"GOAL! GOAL! GOAL!\" graphic print on the front, perfect for young sports enthusiasts.", price: 46, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664223/p0f6jhepllvsxlwzepeg.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664223090 },
  { name: "Boys' Classic Black T-Shirt", description: "A simple and versatile black short-sleeve t-shirt for boys, offering a comfortable fit suitable for everyday casual wear.", price: 10, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664253/bw68c6inwvhzty6saj6a.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664252937 },
  { name: "Women's Black and White Printed Wide-Leg Pants", description: "Stylish women's wide-leg pants with an abstract black and white print, designed with a relaxed fit and side pockets for a chic, modern look.", price: 90, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664282/nxwy3ohrc6in0isydmol.png"], category: "Women", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664282218 },
  { name: "Women's Maroon Zip-Up Jacket", description: "A maroon zip-up jacket for women, featuring a high collar, front pockets, and a cozy, casual style ideal for layering in cooler weather.", price: 95, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664308/ww2nzjdlddmtbcbxzfg0.png"], category: "Women", subCategory: "Winterwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664307901 },
  { name: "Women's Blue Wide-Leg Pants", description: "Elegant blue wide-leg pants for women, featuring a high-rise elastic waistband and a relaxed fit, ideal for both casual and semi-formal outfits.", price: 55, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664382/wuurasvmsdxxcqqfm3w5.png"], category: "Women", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664382532 },
  { name: "Boys' Red USA Sleeveless Sports Set", description: "Athletic boys' sleeveless red top with \"USA\" lettering, paired with matching red shorts, perfect for sports and active play.", price: 36, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664407/h1pbzs9t1zswmgp7lxvs.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664406899 },
  { name: "Boys' Pikachu Baseball Jersey", description: "White short-sleeve baseball jersey for boys, designed with black pinstripes, yellow buttons, and a Pikachu patch on the chest for a playful, sporty look.", price: 26, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664432/hvermdjjo1dfddombf0k.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664431980 },
  { name: "Girls' Pink Cropped Dance T-Shirt", description: "Light pink cropped t-shirt for girls, featuring the phrase \"LIFE IS BETTER WHEN YOU DANCE\" printed on the front, offering a fun and motivational style.", price: 23, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664461/tvxk2tqigtpjgqjcotkq.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664460410 },
  { name: "Women's Light Blue Denim Jacket Set", description: "A trendy women's outfit featuring a cropped light blue denim jacket paired with high-waisted matching jeans and a white crop top, perfect for a casual and stylish look.", price: 32, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664522/i7nm9r8kwkcx4ui67ixd.png"], category: "Women", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664521741 },
  { name: "Girls' Pastel Floral Print Dress", description: "A charming girls' dress adorned with a pastel floral print, long ruffled sleeves, and a flowy silhouette, ideal for spring or summer occasions.", price: 22, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664555/qxobr0dsoitly7de1ksm.png"], category: "Kids", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664555140 },
  { name: "Men's White Puma Logo T-Shirt", description: "A classic white t-shirt for men featuring a prominent blue Puma logo on the chest, perfect for casual and sporty outfits.", price: 40, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664657/mkun9dejfuegzbwnlz6a.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664657129 },
  { name: "Women's Light Grey V-Neck T-Shirt", description: "A relaxed-fit light grey v-neck t-shirt for women, adorned with a small chest logo, ideal for comfortable everyday wear.", price: 26, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664690/fxlmhlecgmia8eaqhnmn.png"], category: "Women", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664690421 },
  { name: "Women's Teal Nike Track Jacket", description: "A teal full-zip track jacket for women, highlighted by a bold white Nike swoosh logo across the chest, suitable for athletic and casual looks.", price: 35, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664723/iltvjkfriml0et5m9a2v.png"], category: "Women", subCategory: "Winterwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664722514 },
  { name: "Women's Light Pink Puffer Jacket", description: "A stylish light pink puffer jacket for women, featuring a cozy faux fur-lined hood and zip closure, combining warmth with a fashionable touch.", price: 120, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664749/r1wkyskd9lupzvtzxwvg.png"], category: "Women", subCategory: "Winterwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664749460 },
  { name: "Men's Beige Printed Casual Shirt", description: "A stylish men's beige shirt featuring a subtle all-over print and button-down front, perfect for smart-casual occasions or everyday wear.", price: 18, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664818/g5icnfpoyts3heu9x3hf.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664818893 },
  { name: "Men's Black Hooded Sleeveless Jacket", description: "A modern black sleeveless jacket for men, designed with a zip-up front, adjustable hood, and side pockets, ideal for layering over t-shirts for a sporty, casual look.", price: 34, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664845/fqmbjzdhhgvpkrjqb98h.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664845776 },
  { name: "Men's Navy Blue Graphic T-Shirt", description: "A navy blue men's t-shirt accented with a unique vertical graphic print on the left side, offering a trendy twist to classic casual attire.", price: 22, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664875/ynuthy9n8rputgrarq7a.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664875463 },
  { name: "Women's Light Pink Casual Jacket", description: "A stylish light pink casual jacket for women, featuring a relaxed fit, front zip closure, and adjustable hem, perfect for layering over everyday outfits.", price: 40, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664973/c7ggovbquccugwal6whb.png"], category: "Women", subCategory: "Winterwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664972877 },
  { name: "Men's Navy Blue Suede Jacket", description: "A classic navy blue suede jacket for men, featuring a zip-up front and chest zipper pockets, offering a sleek and versatile outerwear option.", price: 35, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747665024/u6rqv89487ypf9fdgukj.png"], category: "Men", subCategory: "Winterwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747665023930 },
  { name: "Men's Olive and Grey Puffer Jacket", description: "A color-blocked puffer jacket for men in shades of olive and grey, designed with a hood, front zip, and side pockets for warmth and comfort in cooler weather.", price: 48, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747665001/gd4dwpwje9zezvlcplpc.png"], category: "Men", subCategory: "Winterwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747665001450 },
  { name: "Girls' Light Pink Printed Joggers", description: "Light pink jogger pants for girls, adorned with an abstract print, an elastic waistband with drawstring, and cuffed ankles for a comfortable and trendy look.", price: 25, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747665050/ogopvxatqura35pakasx.png"], category: "Kids", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747665049679 },
  { name: "Men's Classic Blue Denim Jacket", description: "A timeless blue denim jacket for men, featuring a button-up front, chest flap pockets, and a regular fit, perfect for layering over casual outfits.", price: 29, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747665140/cfmytni7tehyvdlxms7i.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747665140412 },
  { name: "Girls' Black Heart Print Leggings", description: "Black leggings for girls, adorned with a scattered small heart print, offering a playful and comfortable option for everyday wear.", price: 20, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747665165/m5xsfxaoyw54nte9da7t.png"], category: "Women", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747665165070 },
  { name: "Girls' Light Green Paperbag Waist Pants", description: "Light green wide-leg pants for girls, designed with a crinkled texture, elastic paperbag waist, and a matching fabric belt for added style.", price: 10, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747665192/yq4afipgup2ohnve9jkl.png"], category: "Kids", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747665192085 },
  { name: "Women's Light Pink Bomber Jacket", description: "A light pink bomber jacket for women, featuring ribbed cuffs and hem, front zip closure, and side pockets, combining comfort with a trendy look.", price: 85, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747665217/d197elouaeqxxdnwqf97.png"], category: "Women", subCategory: "Winterwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747665216982 },
  { name: "Men's Dark Blue Denim Jacket", description: "A classic men's dark blue denim jacket featuring a button-up front, chest flap pockets with button closures, and a tailored fit, ideal for layering over casual outfits.", price: 35, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747665257/gpyfcbhon658hhiffmj1.png"], category: "Men", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747665256861 },
  { name: "Girls' Blue Paperbag Waist Jeans", description: "Blue jeans for girls featuring a comfortable paperbag-style elastic waistband and back pockets, combining both style and practicality for everyday wear.", price: 15, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664913/vnwv3l2tjtkjmkiyxysz.png"], category: "Kids", subCategory: "Bottomwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664912975 },
  { name: "Men's Mustard Yellow Quilted Jacket", description: "A men's quilted jacket in a vibrant mustard yellow shade, designed with a zip-up front and side pockets, offering warmth and a pop of color for cooler weather.", price: 100, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747664587/hyyznhunhrcbgwiiiu5m.png"], category: "Men", subCategory: "Winterwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747664587633 },
  { name: "Women's Light Blue Short Sleeve Shirt", description: "A light blue women's shirt with short sleeves and a relaxed collar, offering a breezy and effortless style suitable for both casual and smart-casual outfits.", price: 23, image: ["https://res.cloudinary.com/dufsxpqd7/image/upload/v1747822273/knznsowmj9lnpqzrgyma.png"], category: "Women", subCategory: "Topwear", sizes: ["S","M","L","XL","XXL"], bestSeller: false, date: 1747822272524 },
]

const seed = async () => {
  try {
    await mongoose.connect(`${process.env.MONGODB_URI}/FitBae`)
    console.log('✅ MongoDB connected')

    const existing = await productModel.countDocuments()
    if (existing > 0) {
      console.log(`⚠️  Found ${existing} existing products. Clearing...`)
      await productModel.deleteMany({})
      console.log('🗑️  Cleared existing products')
    }

    const inserted = await productModel.insertMany(products)
    console.log(`\n🎉 Successfully seeded ${inserted.length} fashion products!`)
    console.log('   Categories: Men, Women, Kids')
    console.log('   Subcategories: Topwear, Bottomwear, Winterwear')
    console.log('\nAdmin Panel Credentials:')
    console.log('   Email   :', process.env.ADMIN_EMAIL)
    console.log('   Password:', process.env.ADMIN_PASSWORD)

    process.exit(0)
  } catch (err) {
    console.error('❌ Seed failed:', err.message)
    process.exit(1)
  }
}

seed()
